services:
  sftp:
    image: atmoz/sftp
    container_name: sftp
    volumes:
      - ./init.sh:/etc/sftp.d/init.sh:ro
      - ./users.conf:/etc/sftp-users.conf:ro
      - ./upload:/home
    ports:
      - "${LOCAL_SFTP_PORT}:22"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
