services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    env_file: .env
    ports:
      - "${LOCAL_DB_PORT}:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - local-dev

networks:
  local-dev:
    external: true
    name: local-dev
