services:
  minio:
    image: docker.arvancloud.ir/minio/minio:latest
    container_name: minio_container
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PORT_UI}:9001"
    env_file: .env
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - local-dev

networks:
  local-dev:
    external: true
    name: local-dev
